import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import Mouse from "@/components/Mouse";
import Product from "@/components/Product";
import About from "@/components/About";
import Check from "@/components/Check";
import Design from "@/components/Design";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="h-screen snap-y snap-mandatory overflow-y-scroll z-0">
      <Head>
        <title>Logitech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <section className="snap-start">
          <Header />
          <Hero />
        </section>
        <section className="snap-center">
          <Mouse id="mouse" />
        </section>
        <section className="snap-center">
          <Product id="Product" />
        </section>
        <section className="snap-center">
          <About />
        </section>
        <section className="snap-center">
          <Check />
        </section>
        <section className="snap-center">
          <Design />
        </section>
        <section className="snap-center">
          <Footer />
        </section>
      </div>
    </div>
  );
}
