import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import Mouse from "@/components/Mouse";
import Product from "@/components/Product";
import About from "@/components/About";
import Check from "@/components/Check";
import Design from "@/components/Design";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Logitech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Hero />
        <Mouse />
        <Product />
        <About />
        <Check />
        <Design />
        <Footer />
      </div>
    </>
  );
}
